language: python
python:
  - "3.5"
branches:
    only:
        - develop
install:
  - pip install -r requirements.txt
script:
  - make publish
after_success:
  # Only deploy from master branch
  - make github
