language: python
python:
  - 3.6
branches:
    only:
        - develop
install:
  - pip install -r requirements.txt
script:
  - invoke preview
after_success:
  # https://github.com/alrra/travis-scripts/blob/master/docs/github-deploy-keys.md
  - |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    openssl aes-256-cbc \
        -K "$encrypted_087acb168d2e_key" \
        -iv "$encrypted_087acb168d2e_iv" \
        -in ".travis/github_deploy_key.enc" \
        -out "$SSH_FILE" -d
    chmod 600 "$SSH_FILE" \
        && printf "%s\n" \
            "Host github.com" \
            "  IdentityFile $SSH_FILE" \
            "  LogLevel ERROR" >> ~/.ssh/config
  - git remote set-url origin "git@github.com:${TRAVIS_REPO_SLUG}.git"
  - invoke gh_pages
