language: python
python:
  - "3.5"
branches:
    only:
        - develop
install:
  - pip install -r requirements.txt
script:
  - make publish
after_success:
  # https://github.com/alrra/travis-scripts/blob/master/docs/github-deploy-keys.md
  - |
       $(npm bin)/set-up-ssh --key "$encrypted_087acb168d2e_key" \
                             --iv "$encrypted_087acb168d2e_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"
  - make github
